language: python

python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - export PYTHONPATH="$PYTHONPATH:/home/travis/build/manMadeLogic/YourChef"
  - pytest Test/*
  - pytest Test/* > report/unit_test.txt
  - coverage run --source=YourChef.userHelper Test/TestUser.py
  - coverage report -m
  - coverage report > report/user_coverage.txt
  - coverage run --source=YourChef.registration Test/TestRegistration.py
  - coverage report -m
  - coverage report > report/registration_coverage.txt
  - coverage run --source=YourChef.gmHelper Test/TestGM.py
  - coverage report -m
  - coverage report > report/gm_coverage.txt
  - coverage run --source=YourChef.menu Test/TestMenu.py
  - coverage report -m
  - coverage report > report/menu_coverage.txt
after_success:
  - coveralls
