language: python

python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest Test/TestUser.py
  - pytest Test/TestRegistration.py
  - coverage report -m
after_success:
  - coveralls
