#!/bin/bash

added_modified=$(git diff --cached --diff-filter=AM --name-only | grep .py$)

[[ -z $added_modified ]] && exit 0

pyflakes $added_modified
pyflakes $added_modified > report/pre_output.txt
